-- Verified official website URLs (sourced from GOV.UK / Ofsted school records)
UPDATE grammar_schools SET website = 'https://www.ags.bucks.sch.uk'                WHERE name = 'Aylesbury Grammar School';
UPDATE grammar_schools SET website = 'https://www.ahs.bucks.sch.uk'                WHERE name = 'Aylesbury High School';
UPDATE grammar_schools SET website = 'https://www.beaconsfieldhigh.school'         WHERE name = 'Beaconsfield High School';
UPDATE grammar_schools SET website = 'https://www.bishopwordsworths.org.uk'        WHERE name = 'Bishop Wordsworth''s School';
UPDATE grammar_schools SET website = 'https://www.caistorgrammar.com'              WHERE name = 'Caistor Grammar School';
UPDATE grammar_schools SET website = 'https://www.cchs.co.uk'                      WHERE name = 'Chelmsford County High School for Girls';
UPDATE grammar_schools SET website = 'https://www.cheshamgrammar.org'              WHERE name = 'Chesham Grammar School';
UPDATE grammar_schools SET website = 'https://www.cchsg.com'                       WHERE name = 'Colchester County High School for Girls';
UPDATE grammar_schools SET website = 'https://www.crgs.co.uk'                      WHERE name = 'Colchester Royal Grammar School';
UPDATE grammar_schools SET website = 'https://www.damealiceowens.herts.sch.uk'     WHERE name = 'Dame Alice Owen''s School';
UPDATE grammar_schools SET website = 'https://www.dartfordgrammarschool.org.uk'    WHERE name = 'Dartford Grammar School';
UPDATE grammar_schools SET website = 'https://www.dartfordgrammargirls.org.uk'     WHERE name = 'Dartford Grammar School for Girls';
UPDATE grammar_schools SET website = 'https://www.challoners.com'                  WHERE name = 'Dr Challoner''s Grammar School';
UPDATE grammar_schools SET website = 'https://www.challonershigh.com'              WHERE name = 'Dr Challoner''s High School';
UPDATE grammar_schools SET website = 'https://www.hbschool.org.uk'                 WHERE name = 'Henrietta Barnett School';
UPDATE grammar_schools SET website = 'https://www.invicta.viat.org.uk'             WHERE name = 'Invicta Grammar School';
UPDATE grammar_schools SET website = 'https://www.jhgs.bucks.sch.uk'               WHERE name = 'John Hampden Grammar School';
UPDATE grammar_schools SET website = 'https://www.kendrick.reading.sch.uk'         WHERE name = 'Kendrick School';
UPDATE grammar_schools SET website = 'https://www.keaschool.org.uk'                WHERE name = 'King Edward VI Aston School';
UPDATE grammar_schools SET website = 'https://www.kefw.org'                        WHERE name = 'King Edward VI Five Ways School';
UPDATE grammar_schools SET website = 'https://www.kegs.org.uk'                     WHERE name = 'King Edward VI Grammar School';
UPDATE grammar_schools SET website = 'https://www.handsworth.bham.sch.uk'          WHERE name = 'King Edward VI Handsworth School';
UPDATE grammar_schools SET website = 'https://www.kehs.org.uk'                     WHERE name = 'King Edward VI High School for Girls';
UPDATE grammar_schools SET website = 'https://www.kes.org.uk'                      WHERE name = 'King Edward''s School';
UPDATE grammar_schools SET website = 'https://lincolnchristshospitalschool.co.uk'  WHERE name = 'Lincoln Christ''s Hospital School';
UPDATE grammar_schools SET website = 'https://mgs.kent.sch.uk'                     WHERE name = 'Maidstone Grammar School';
UPDATE grammar_schools SET website = 'https://www.newsteadwood.co.uk'              WHERE name = 'Newstead Wood School';
UPDATE grammar_schools SET website = 'https://www.nonsuchschool.org'               WHERE name = 'Nonsuch High School for Girls';
UPDATE grammar_schools SET website = 'https://www.patesgs.org'                     WHERE name = 'Pates Grammar School';
UPDATE grammar_schools SET website = 'https://www.qebarnet.co.uk'                  WHERE name = 'Queen Elizabeth''s School Barnet';
UPDATE grammar_schools SET website = 'https://www.reading-school.co.uk'            WHERE name = 'Reading School';
UPDATE grammar_schools SET website = 'https://www.richardhale.herts.sch.uk'        WHERE name = 'Richard Hale School';
UPDATE grammar_schools SET website = 'https://www.royallatin.org'                  WHERE name = 'Royal Latin School';
UPDATE grammar_schools SET website = 'https://www.langton.kent.sch.uk'             WHERE name = 'Simon Langton Girls'' Grammar School';
UPDATE grammar_schools SET website = 'https://www.langton.kent.sch.uk'             WHERE name = 'Simon Langton Grammar School for Boys';
UPDATE grammar_schools SET website = 'https://www.swbgs.com'                       WHERE name = 'Sir William Borlase''s Grammar School';
UPDATE grammar_schools SET website = 'https://www.swgs.wilts.sch.uk'               WHERE name = 'South Wilts Grammar School';
UPDATE grammar_schools SET website = 'https://www.saintolaves.net'                 WHERE name = 'St Olave''s Grammar School';
UPDATE grammar_schools SET website = 'https://www.suttongrammar.sutton.sch.uk'     WHERE name = 'Sutton Grammar School';
UPDATE grammar_schools SET website = 'https://cryptschool.org'                     WHERE name = 'The Crypt School';
UPDATE grammar_schools SET website = 'https://www.judd.online'                     WHERE name = 'The Judd School';
UPDATE grammar_schools SET website = 'https://www.skinners-school.co.uk'           WHERE name = 'The Skinners'' School';
UPDATE grammar_schools SET website = 'https://www.tiffingirls.org'                 WHERE name = 'Tiffin Girls'' School';
UPDATE grammar_schools SET website = 'https://www.tiffinschool.co.uk'              WHERE name = 'Tiffin School';
UPDATE grammar_schools SET website = 'https://www.tgs.kent.sch.uk'                 WHERE name = 'Tonbridge Grammar School';
UPDATE grammar_schools SET website = 'https://www.wcgs-sutton.co.uk'               WHERE name = 'Wallington County Grammar School';
UPDATE grammar_schools SET website = 'https://www.wallingtongirls.org.uk'          WHERE name = 'Wallington High School for Girls';
UPDATE grammar_schools SET website = 'https://www.wchs.co.uk'                      WHERE name = 'Westcliff High School for Boys';
UPDATE grammar_schools SET website = 'https://www.whsg.info'                       WHERE name = 'Westcliff High School for Girls';
UPDATE grammar_schools SET website = 'https://www.wilsons.school'                  WHERE name = 'Wilson''s School';
UPDATE grammar_schools SET website = 'https://www.whs.bucks.sch.uk'                WHERE name = 'Wycombe High School';